# Generated by Django 5.1.4 on 2025-05-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='display_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='max_votes_allowed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='ranking',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='vote_count',
            field=models.PositiveIntegerField(),
        ),
    ]
