# Generated by Django 5.1.4 on 2025-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_alter_ballot_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
    ]
