# Generated by Django 5.1.4 on 2025-05-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_candidate_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='ballot',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['ranking']},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='election.election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nomination_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='election.admin'),
        ),
        migrations.AlterField(
            model_name='result',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='election.ballot'),
        ),
        migrations.AlterField(
            model_name='result',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='election.candidate'),
        ),
        migrations.AlterField(
            model_name='result',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='election.election'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.ballot'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'election', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('ballot', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('ballot', 'user', 'candidate')},
        ),
    ]
